/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>
#include "stm.h"
#include "GPIO_Driver.h"

/*
 * delay function
 */
void delay(void){
	for (volatile uint32_t i = 0; i < 500000; i++);
}

/*
 * Toggle onboard LED PA5
 */
void oneA(){
	// TODO: Initialize PA5 as output:
	GPIO_Init_PortA(5,1);
	while(1){
		// TODO: Toggle PA5:
		HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5)
		delay();
	}
}

/*
 * Toggle external LEDs on PC5, PC6 and PC8
 */
void oneB(){
	// TODO: Initialize PC5, PC6 and PC8:
	GPIO_Init_PortC(5,1);
	GPIO_Init_PortC(6,1);
	GPIO_Init_PortC(8,1);
	while(1){
		// TODO: Toggle PC5, PC6 and PC8:
		GPIO_ToggleOutputPinC(5);
		GPIO_ToggleOutputPinC(6);
		GPIO_ToggleOutputPinC(8);
		delay();
	}
}

/*
 * main function
 */
int main(void){
	// TODO: Call functions to toggle LEDs
	oneA();
}
